#!/usr/bin/env python3
"""
Generate and check the wiki's derived artifacts.

    build.py check     report every inconsistency, change nothing (exit 1 if any)
    build.py write     regenerate glossary + search-index.json, sync category rows,
                       the README key-terms block, and README counts
    build.py report    reverse index for Wiki-Sources col L, and the gap report

Design notes worth keeping:

* The full per-category tables live in glossary/categories.md (moved out of the
  README Sep 2026, so the README shows a few key terms instead of all of them).
  Row ORDER inside a category there is hand-curated and pedagogical (LLMs before
  SLMs before Local LLMs). The generator syncs row CONTENT in place and appends
  new entries at the end of their category. It never reorders.
* The README's Concepts section is a generated block: per category, the terms
  other entries link to most (ties broken by that hand-curated order), plus a
  link to the full category list. Derived, so it cannot go stale.
* The glossary is alphabetical and fully derived, so it is regenerated whole.
* `check` is the mode that runs on every publish. `write` is only for when
  check reports a fixable difference.
"""
import json, re, subprocess, sys
from collections import Counter, defaultdict
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from entry_meta import load, ROOT, stray_scripts  # noqa: E402

README = ROOT / "README.md"
CATALOG = ROOT / "glossary" / "categories.md"
KEY_TERMS_N = 4
# Optional overrides for the derived key terms: pin a slug to the front of its
# category, or exclude one. Empty by default -- prefer the derived selection.
KEY_TERMS_PIN = {"Foundations": ["large-language-models"]}  # user decision Sep 17 2026: the most basic entry, rarely linked because other entries mention LLMs in passing
KEY_TERMS_EXCLUDE = set() # {"some-slug"}
KEY_START = "<!-- key-terms:start (generated by scripts/build.py write; edit glossary/categories.md, not this block) -->"
KEY_END = "<!-- key-terms:end -->"
GLOSSARY = ROOT / "glossary" / "index.md"
INDEX = ROOT / "search-index.json"
SEARCH = ROOT / "search.html"
TEMPLATE = ROOT / "scripts" / "search-template.html"
CONCEPTS = ROOT / "concepts"
REGISTER = ROOT / "glossary" / "register.md"
EXPORT = ROOT / "scripts" / "tracker-export.tsv"

TERM_STATUS = {
    "established": "Recognized term of art, in independent use.",
    "emerging":    "Real and in use, but definitions still vary between sources.",
    "house":       "This wiki's own label; not citable as a term of art.",
    "vendor":      "Coined by a single vendor \u2014 published, if at all, under a neutral name.",
    "unassessed":  "Candidate not yet put through the term-status checks.",
    "declined":    "Considered and turned down \u2014 not a term this wiki will publish.",
    "covered":     "A real term, already covered by another entry \u2014 findable there as an alias.",
}


def read_export():
    """The tracker sheet's terms, as exported. Source of truth for the register."""
    if not EXPORT.exists():
        return []
    rows = []
    for line in EXPORT.read_text().splitlines():
        if not line.strip() or line.startswith("#"):
            continue
        parts = (line.split("\t") + ["", "", "", ""])[:5]
        rows.append({"term": parts[0], "published": parts[1] == "yes",
                     "status": parts[2], "note": parts[3], "flag": parts[4]})
    return rows

# Closed vocabulary. Pruned 26 -> 12 on Aug 31 2026; "LLM" was dropped outright
# (25 of 81 entries — a tag that matches a third of the corpus discriminates nothing,
# the same reason "ai" is a stopword in the search ranking). Adding a tag is a
# deliberate act: extend this list, then re-tag, rather than inventing one in a file.
# Term establishment status. Answers "is this a real term?" — a DIFFERENT question from
# the entry's `## Confidence level`, which answers "how good is the evidence for these
# claims?". Conflating them is why 26 entries once carried "Established"/"Emerging" in a
# field meant for evidence strength. A well-established term can have weak evidence
# (Cognitive Offloading) and a house term can have excellent sources (Custodial Agency).
STATUS = {
    "established": "> **Term status — Established.**",
    "emerging":    "> **Term status — Emerging.**",
    "house":       "> **Term status — House term.**",
    "vendor":      "> **Term status — Vendor-coined.**",
}

VOCAB = ["AI Literacy", "Agents", "Architecture", "Data Governance", "Ethics", "Evaluation",
         "Model Behavior", "Privacy", "Prompting", "Regulatory", "Safety", "Security"]

ROW_RE = re.compile(r"^\|\s*\[([^\]]+)\]\(\.\./concepts/([a-z0-9-]+)\.md\)\s*\|\s*(.*?)\s*\|\s*✅\s*(v[\d.]+)\s*\|\s*$")
SECTION_RE = re.compile(r"^### (.+)$")
COUNT_RE = re.compile(r"(\*\*Status:\*\* Phase \d+ — )(\d+)( concepts)")

# README prose counts that live in running text rather than in a table row.
# (label, pattern with the number as group 2, value from the corpus). Shared by
# write() and check(), so the writer and the assertion cannot disagree about
# which sentence or which number they mean. They drifted to 81/405 at a corpus
# of 95/507 while hand-maintained; write() now owns them and check() confirms.
def _alias_count(entries):
    return len({a for e in entries for a in (e.get("aliases") or [])})

PROSE_COUNTS = (
    ("glossary term count", re.compile(r"(<br>)(\d+)( terms, A–Z)"), len),
    ("alias count", re.compile(r"(Matches )(\d+)( synonyms)"), _alias_count),
)


# ---------- README parsing ----------

def read_readme_rows():
    """-> {slug: (term, short, version, line_no)}, and {category: [slug,...]} in file order.

    Reads glossary/categories.md, which holds the full per-category tables. (The
    name is historical: these tables lived in the README until Sep 2026.)"""
    lines = CATALOG.read_text().splitlines()
    rows, order, cat = {}, defaultdict(list), None
    for i, line in enumerate(lines):
        m = SECTION_RE.match(line)
        if m:
            cat = m.group(1).strip()
            continue
        m = ROW_RE.match(line)
        if m and cat:
            rows[m.group(2)] = (m.group(1), m.group(3), m.group(4), i)
            order[cat].append(m.group(2))
    return lines, rows, order


# ---------- checks ----------

def check(entries):
    problems = []
    by_slug = {e["slug"]: e for e in entries}
    lines, rrows, rorder = read_readme_rows()

    # 0. README prose counts. write() sets them; this confirms the result, and
    #    catches a reworded sentence the writer can no longer find.
    rtext = README.read_text()
    for what, pat, value in PROSE_COUNTS:
        m = pat.search(rtext)
        want = value(entries)
        if not m:
            problems.append(f"readme: prose {what} sentence not found")
        elif int(m.group(2)) != want:
            problems.append(f"readme: prose {what} says {m.group(2)}, corpus has {want} (run `build.py write`)")

    # 0b. the badge alt text states the assessment date; the PNG is a snapshot of a
    #     live reading, so a re-issued declaration leaves both silently stale.
    decl = ROOT.parent / "authorship-meter" / "declarations" / "applied-ai-concepts.json"
    if decl.exists():
        import json, datetime
        d = json.loads(decl.read_text())
        want = datetime.date.fromisoformat(d["assessed_at"]).strftime("%B %-d %Y")
        if f"assessed {want}" not in rtext:
            problems.append(f"readme: badge alt text does not state the declaration's "
                            f"assessed date ({want})")

    # 0c. tracker export vs repo. The register is published from the export, so a stale
    #     export becomes a false public claim -- the old hand-maintained list had drifted
    #     to 13 already-published terms before this check existed.
    _home = alias_home(entries)
    rows = read_export()
    if not rows:
        problems.append(f"export: {EXPORT.relative_to(ROOT)} missing — the term register cannot be built")
    else:
        by_term = {e["term"]: e for e in entries}
        exp = {r["term"]: r for r in rows}
        for term, e in sorted(by_term.items()):
            r = exp.get(term)
            if not r:
                problems.append(f"export: published entry '{term}' is absent from the tracker export")
            elif not r["published"]:
                problems.append(f"export: '{term}' is published but the export says it is not")
            elif r["status"] != e.get("established"):
                problems.append(f"export: '{term}' status '{r['status']}' != entry's "
                                f"'{e.get('established')}'")
        for term, r in sorted(exp.items()):
            if r["published"] and term not in by_term:
                problems.append(f"export: '{term}' marked published but no such entry exists")
            if r["status"] not in TERM_STATUS:
                problems.append(f"export: '{term}' has unknown status '{r['status']}'")
            # `covered` asserts the term lives somewhere else. Without an alias resolving
            # to a published entry that is an unfalsifiable dismissal, and the register
            # would render it with no destination -- so require the alias to exist.
            if r["status"] == "covered" and not _home.get(term.lower()):
                problems.append(f"export: '{term}' is marked covered but no published entry "
                                f"carries it as an alias — add the alias or change the status")
            # The tracker's On Github Flag is HAND-MAINTAINED; the Pipeline State column
            # beside it is DERIVED from Term Status. They agree today, and nothing stops
            # them drifting -- so assert the correspondence.
            #
            # Deliberately NOT checked here: "published but status covered/declined". Three
            # seeded faults confirmed the existing checks above already catch every case of
            # that (via the status mismatch, or via 'no such entry exists'), so a rule for it
            # would be dead code -- the failure this file's docstring warns about.
            #
            # What IS unchecked without the flag column: the sheet sorts into three blocks,
            # and only the flag says which. A fold left as `TBD` derives the right state and
            # publishes nothing wrong, so it is invisible to every other check -- while
            # sitting in the wrong block in the sheet. That happened once (Pseudonymization,
            # Sep 2026) and was found by hand.
            if r["flag"] and r["flag"] not in ("X", "TBD", "N/A"):
                problems.append(f"export: '{term}' has unknown On Github Flag '{r['flag']}' — "
                                f"expected X (published), TBD (queued) or N/A (not publishing)")
            elif r["status"] in ("covered", "declined") and r["flag"] != "N/A":
                problems.append(f"export: '{term}' is '{r['status']}' but its flag is "
                                f"'{r['flag']}' — a term that will not be published must be "
                                f"flagged N/A, or it sorts into the wrong block")
            elif r["flag"] == "N/A" and r["status"] not in ("covered", "declined"):
                problems.append(f"export: '{term}' is flagged N/A but its status is "
                                f"'{r['status']}' — flag says it will not be published, "
                                f"status says it is still a candidate")

    # 0d. stray scripts and invisible characters in anything published.
    #     Blocking rather than advisory: a CJK character in English prose or a
    #     Cyrillic homoglyph in a term is a defect, never a judgement call, and
    #     the ranges are chosen so accented Latin, Greek and symbols never hit.
    #     Two shipped-adjacent instances in three releases -- one in entry prose,
    #     one in a registry cell -- and every other check was blind to both,
    #     because the text is structurally valid and correctly spelled.
    #     glossary/ is included deliberately even though it is generated: the
    #     register renders the tracker's status notes verbatim, so sweeping it is
    #     what catches a stray character that entered through a SHEET cell rather
    #     than through a file. That is the path the v1.30 instance took.
    for f in sorted(list(CONCEPTS.glob("*.md")) + list((ROOT / "notes").glob("*.md"))
                    + list((ROOT / "glossary").glob("*.md"))
                    + [ROOT / "README.md", ROOT / "CONTRIBUTING.md"]):
        if not f.exists():
            continue
        text = f.read_text(encoding="utf-8")
        seen = {}
        for ch, cp, name in stray_scripts(text):
            seen.setdefault((ch, cp, name), 0)
            seen[(ch, cp, name)] += 1
        for (ch, cp, name), n in sorted(seen.items()):
            line = next((i for i, l in enumerate(text.splitlines(), 1) if ch in l), "?")
            problems.append(f"charset: {f.name}:{line} contains {name} character "
                            f"{ch!r} (U+{cp:04X}){'' if n == 1 else f', {n}x'} — "
                            f"non-Latin script or invisible character in published content")

    # 1. schema completeness
    for e in entries:
        miss = [k for k in ("term", "essence", "version") if not e.get(k)]
        if miss:
            problems.append(f"derivation: {e['slug']} missing {', '.join(miss)}")
        if not e.get("authored"):
            problems.append(f"schema: {e['slug']} has no <!--meta block")
        for k in ("category", "short", "aliases", "tags"):
            if not e.get(k):
                problems.append(f"schema: {e['slug']} missing authored field '{k}'")
        if not e.get("confidence"):
            problems.append(f"derivation: {e['slug']} confidence level does not open with a "
                            f"parseable rating (high / medium-high / medium / low-medium / low / split)")
        st = e.get("established")
        if not st:
            problems.append(f"schema: {e['slug']} missing authored field 'established'")
        elif st not in STATUS:
            problems.append(f"schema: {e['slug']} established '{st}' not in {sorted(STATUS)}")
        else:
            # the visible line and the meta value must agree — two surfaces, one fact
            body = (CONCEPTS / f"{e['slug']}.md").read_text()
            shown = [l for l in body.splitlines() if l.startswith("> **Term status")]
            if len(shown) != 1:
                problems.append(f"status: {e['slug']} has {len(shown)} visible term-status lines, want 1")
            elif not shown[0].startswith(STATUS[st]):
                problems.append(f"status: {e['slug']} meta says '{st}' but the visible line disagrees")
        for t in e.get("tags") or []:
            if t not in VOCAB:
                problems.append(f"tag: {e['slug']} '{t}' is not in the closed vocabulary")

    # 2. README round-trip (term, category, short, version)
    for slug, (term, short, ver, _) in rrows.items():
        e = by_slug.get(slug)
        if not e:
            problems.append(f"categories: row for {slug} but no such entry")
            continue
        if e["term"] != term:
            problems.append(f"categories term: {slug} H1='{e['term']}' categories.md='{term}'")
        if e.get("short") != short:
            problems.append(f"categories short: {slug} differs from meta block")
        if e["version"] != ver:
            problems.append(f"categories version: {slug} entry={e['version']} categories.md={ver}")
    for slug in by_slug.keys() - rrows.keys():
        problems.append(f"categories: {slug} published but absent from glossary/categories.md")
    for cat, slugs in rorder.items():
        for slug in slugs:
            e = by_slug.get(slug)
            if e and e.get("category") and e["category"] != cat:
                problems.append(f"categories: {slug} meta='{e['category']}' categories.md section='{cat}'")
    rt = README.read_text()
    if KEY_START not in rt or KEY_END not in rt:
        problems.append("readme: key-terms block markers not found")
    elif rt[rt.index(KEY_START):rt.index(KEY_END) + len(KEY_END)] != key_terms_block(entries):
        problems.append("readme: key-terms block out of date (run `build.py write`)")

    # 3. glossary
    want = "\n".join(glossary_rows(entries))
    have = "\n".join(l for l in GLOSSARY.read_text().splitlines() if l.startswith("| ["))
    if want != have:
        problems.append("glossary: out of sync with entries (run `build.py write`)")

    # 4. counts
    m = COUNT_RE.search(README.read_text())
    if not m:
        problems.append("readme: concept-count line not found")
    elif int(m.group(2)) != len(entries):
        problems.append(f"readme count: says {m.group(2)}, corpus has {len(entries)}")

    # 5. links + anchor-text mislinks
    problems += link_problems(entries, by_slug)

    # 6. alias rules
    problems += alias_problems(entries)

    # 7. generated page sanity
    problems += page_problems()
    return problems


def page_problems():
    """Catch the failure that shipped a broken search page: an identifier used but
    never declared.

    A silent no-op string replace left `$tags` referenced and undeclared, which threw
    a ReferenceError partway down the script — killing the filter chips AND the
    addEventListener below it, so typing did nothing. Nothing caught it: the file was
    valid HTML, every link resolved, and the JSON was correct. This check is six lines
    and would have failed the publish.
    """
    out = []
    if not SEARCH.exists():
        return out
    src = SEARCH.read_text()
    body = src.split("<script>")[-1]
    used = set(re.findall(r"\$[A-Za-z_][A-Za-z0-9_]*", body))
    declared = set(re.findall(r"(?:const|let|var)\s+(\$[A-Za-z_][A-Za-z0-9_]*)", body))
    declared |= set(re.findall(r",\s*(\$[A-Za-z_][A-Za-z0-9_]*)\s*=", body))
    for name in sorted(used - declared):
        out.append(f"search.html: `{name}` is used but never declared "
                   f"(ReferenceError would kill everything after it)")
    for el in sorted(set(re.findall(r'getElementById\("([^"]+)"\)', body))):
        if f'id="{el}"' not in src:
            out.append(f"search.html: getElementById(\"{el}\") but no element has that id")
    return out


def link_problems(entries, by_slug):
    """Broken links, plus two anchor-text checks with deliberately different strictness.

    Related-concepts bullets follow an exact-title convention, so a mismatch there
    is a hard failure. Inline prose links are legitimately paraphrased ("[tools]",
    "[human approval]"), so flagging every loose anchor is pure noise — the useful
    signal is narrower: an anchor that matches some OTHER entry and not the target.
    That is what a stale link looks like after the real target gets published, and
    it is invisible to a broken-link check because the old target still resolves.
    """
    out = []
    norm = lambda x: set(re.sub(r"[^a-z0-9]+", " ", x.lower()).split())
    titles = {e["slug"]: e["term"] for e in entries}
    words = {e["slug"]: norm(e["term"]) | set().union(*[norm(a) for a in (e.get("aliases") or [])] or [set()])
             for e in entries}
    for p in sorted(ROOT.rglob("*.md")):
        if ".git" in p.parts or p.name == "CONTEXT.md":
            continue
        for line in p.read_text().splitlines():
            bullet = line.lstrip().startswith("- [")
            for m in re.finditer(r"\[([^\]]+)\]\(([^)]+\.md)\)", line):
                anchor, target = m.group(1), m.group(2).split("#")[0]
                if not (p.parent / target).exists():
                    out.append(f"broken link: {p.relative_to(ROOT)} -> {target}")
                    continue
                slug = Path(target).stem
                if slug not in titles:
                    continue
                a, t = norm(anchor), norm(titles[slug])
                if bullet and not (a & t):
                    out.append(f"mislink (related-concepts): {p.relative_to(ROOT)} "
                               f"[{anchor}] -> {slug} ('{titles[slug]}')")
    return out


def inline_anchor_review(entries):
    """Inline anchors sharing no words with their target — a REVIEW list, not a check.

    Tried as a hard check first and it scored 1 true positive against 18 false ones,
    because inline prose legitimately paraphrases ("[tools]", "[human approval]").
    The one real find — [shadow] -> ai-governance, written before shadow-ai.md
    existed — came from reading the list, not from the rule. So the rule earns a
    place in `report`, skimmed after a publish, and not a place in the gate.
    """
    norm = lambda x: set(re.sub(r"[^a-z0-9]+", " ", x.lower()).split())
    titles = {e["slug"]: e["term"] for e in entries}
    out = []
    for p in sorted(ROOT.rglob("*.md")):
        if ".git" in p.parts or p.name == "CONTEXT.md":
            continue
        for line in p.read_text().splitlines():
            if line.lstrip().startswith("- ["):
                continue
            for m in re.finditer(r"\[([^\]]+)\]\(([^)]+\.md)\)", line):
                slug = Path(m.group(2).split("#")[0]).stem
                if slug in titles and not (norm(m.group(1)) & norm(titles[slug])):
                    out.append(f"  {p.relative_to(ROOT)}: [{m.group(1)}] -> {slug}")
    return out


def alias_problems(entries):
    out = []
    norm = lambda x: re.sub(r"[^a-z0-9]+", " ", x.lower()).strip()
    titles = {norm(e["term"]): e["slug"] for e in entries}
    seen = defaultdict(list)
    for e in entries:
        for a in e.get("aliases") or []:
            n = norm(a)
            seen[n].append(e["slug"])
            owner = titles.get(n)
            if owner and owner != e["slug"]:
                out.append(f"alias collision: {e['slug']} '{a}' is the title of {owner}")
            if n == norm(e["term"]):
                out.append(f"alias restates title: {e['slug']} '{a}'")
    for n, slugs in seen.items():
        if len(slugs) > 1:
            out.append(f"alias shared: '{n}' -> {', '.join(slugs)}")
    return out


# ---------- generation ----------

def glossary_rows(entries):
    return [f"| [{e['term']}](../concepts/{e['slug']}.md) | {e['essence'].rstrip('.')} |"
            for e in sorted(entries, key=lambda e: e["term"].lower())]


def alias_home(entries):
    """-> {lowercased alias: entry} for every published entry's aliases.

    Used to resolve where a `covered` term actually lives. The alias is the mechanism
    by which the term is findable, so it is also the right thing to derive the pointer
    from -- rather than restating the target in prose that can drift from it.
    """
    out = {}
    for e in entries:
        for a in e.get("aliases") or []:
            out.setdefault(a.strip().lower(), e)
    return out


def register_page(entries):
    """The public term register: EVERY tracked term with its status, published or not.

    Generated, never authored -- the tracker sheet is the source, exported to
    scripts/tracker-export.tsv. Its job is to make the curation filter visible:
    a reader can see what was admitted, what is queued, and what was coined by a
    vendor and so will not be published under that name.
    """
    rows = read_export()
    by_term = {e["term"]: e for e in entries}
    counts = Counter(r["status"] for r in rows)
    n_pub = sum(1 for r in rows if r["published"])

    out = ["# Term register", "",
           "Every term this wiki tracks, with its status \u2014 **including the ones that are not "
           "published, and the ones that will not be.**", "",
           "The field names things faster than it settles them, and a glossary that repeats every new "
           "label without comment is a list of buzzwords. So each term is judged on whether it is a "
           "*real term*. That is a separate question from how good the evidence is for the claims "
           "inside an entry, which each entry states for itself in its own confidence level.", "",
           f"**{len(rows)} terms tracked \u2014 {n_pub} published, {len(rows) - n_pub} not.** "
           "See [how terms are admitted](../CONTRIBUTING.md#term-status--the-admission-test).", "",
           "| Status | Meaning | Count |", "|---|---|---|"]
    for k in ("established", "emerging", "house", "vendor", "unassessed", "declined", "covered"):
        if counts.get(k):
            out.append(f"| `{k}` | {TERM_STATUS[k]} | {counts[k]} |")
    # A `covered` term is covered BECAUSE it is an alias of a published entry, so the
    # pointer is derived from the alias index rather than authored a second time in the
    # note. That makes the alias the single source of truth: retarget the alias and the
    # register follows. `check` fails if a covered term has no alias to resolve to.
    home = alias_home(entries)
    out += ["", "---", "", "| Term | Status | Published | Notes |", "|---|---|---|---|"]
    for r in sorted(rows, key=lambda r: r["term"].lower()):
        e = by_term.get(r["term"])
        name = f"[{r['term']}](../concepts/{e['slug']}.md)" if e else r["term"]
        # "not yet" promises a future entry, which is false for a declined or covered
        # term -- and the register exists precisely to show "the ones that will not be".
        if r["published"]:
            pub = "yes"
        elif r["status"] == "declined":
            pub = "**no \u2014 declined**"
        elif r["status"] == "covered":
            h = home.get(r["term"].lower())
            pub = (f"**covered by [{h['term']}](../concepts/{h['slug']}.md)**" if h
                   else "**no \u2014 covered elsewhere**")
        else:
            pub = "not yet"
        out.append(f"| {name} | `{r['status']}` | {pub} | {r['note'] or ''} |")
    out += ["", "---", "",
            "*Generated from the term tracker by `scripts/build.py write`. Do not edit by hand.*", ""]
    return "\n".join(out)


def write(entries):
    changed = []
    by_slug = {e["slug"]: e for e in entries}

    # glossary — fully regenerated (alphabetical, derived)
    head = ["# Glossary", "", "Quick-reference index of all concepts. Follow links for full entries.",
            "", "---", "", "| Term | One-line essence |", "|---|---|"]
    new_gloss = "\n".join(head + glossary_rows(entries)) + "\n"
    if GLOSSARY.read_text() != new_gloss:
        GLOSSARY.write_text(new_gloss)
        changed.append(f"glossary/index.md ({len(entries)} rows)")

    # README — sync row content in place, append new rows at end of their category
    lines, rrows, rorder = read_readme_rows()
    edits = 0
    for slug, (term, short, ver, i) in rrows.items():
        e = by_slug.get(slug)
        if not e:
            continue
        want = f"| [{e['term']}](../concepts/{slug}.md) | {e['short']} | ✅ {e['version']} |"
        if lines[i] != want:
            lines[i] = want
            edits += 1
    missing = [s for s in by_slug if s not in rrows]
    for slug in missing:
        e = by_slug[slug]
        idxs = [i for s in rorder.get(e["category"], []) for (_, _, _, i) in [rrows[s]]]
        if not idxs:
            changed.append(f"!! {slug}: category '{e['category']}' has no README section — add by hand")
            continue
        row = f"| [{e['term']}](../concepts/{slug}.md) | {e['short']} | ✅ {e['version']} |"
        lines.insert(max(idxs) + 1, row)
        lines, rrows, rorder = _reparse(lines)
        edits += 1
    cat_text = "\n".join(lines) + "\n"
    if cat_text != CATALOG.read_text():
        CATALOG.write_text(cat_text)
        changed.append(f"glossary/categories.md ({edits} row(s) synced)")
    text = README.read_text()
    if KEY_START in text and KEY_END in text:
        text = text[:text.index(KEY_START)] + key_terms_block(entries) + text[text.index(KEY_END) + len(KEY_END):]
    else:
        changed.append("!! README key-terms block markers not found — add them by hand")
    text = COUNT_RE.sub(lambda m: f"{m.group(1)}{len(entries)}{m.group(3)}", text)
    for what, pat, value in PROSE_COUNTS:
        n = value(entries)
        text, hits = pat.subn(lambda m, n=n: f"{m.group(1)}{n}{m.group(3)}", text)
        if hits != 1:
            # Loud, never silent: a sentence that was reworded would otherwise
            # simply stop being maintained.
            changed.append(f"!! README prose {what}: expected 1 sentence, found {hits} — fix by hand")
    if text != README.read_text():
        README.write_text(text)
        changed.append(f"README.md (key terms + counts -> {len(entries)})")

    # search index
    payload = {"schema": 1, "count": len(entries),
               "entries": [{k: e[k] for k in ("slug", "term", "category", "essence", "short",
                                              "aliases", "tags", "version", "updated", "related",
                                              "sources", "path")} for e in
                           sorted(entries, key=lambda e: e["term"].lower())]}
    new_idx = json.dumps(payload, indent=2, ensure_ascii=False) + "\n"
    if not INDEX.exists() or INDEX.read_text() != new_idx:
        INDEX.write_text(new_idx)
        changed.append(f"search-index.json ({len(entries)} entries, "
                       f"{sum(len(e['aliases']) for e in entries)} aliases)")

    # search.html — index INLINED, not fetched. GitHub Pages is not enabled on this
    # repo, so the page has to work when opened from a clone over file://, where
    # fetch() is blocked by CORS. Inlining costs a duplicate copy of generated data,
    # which cannot drift because this function writes both.
    if TEMPLATE.exists():
        remote = subprocess.run(["git", "remote", "get-url", "origin"], cwd=ROOT,
                                capture_output=True, text=True).stdout.strip()
        m = re.search(r"github\.com[:/]([^/]+/[^/.]+)", remote)
        blob = f"https://github.com/{m.group(1)}/blob/main/" if m else ""
        page = (TEMPLATE.read_text()
                .replace("__BLOB__", blob)
                .replace("__INDEX__", json.dumps(payload, ensure_ascii=False, separators=(",", ":")))
                .replace("__COUNT__", str(len(entries)))
                .replace("__ALIASES__", str(sum(len(e["aliases"]) for e in entries)))
                .replace("__TAGS__", json.dumps(sorted(VOCAB))))
        if not SEARCH.exists() or SEARCH.read_text() != page:
            SEARCH.write_text(page)
            changed.append(f"search.html ({len(page)//1024} KB, self-contained)")

    rows = read_export()
    if rows:
        page = register_page(entries)
        if not REGISTER.exists() or REGISTER.read_text() != page:
            REGISTER.write_text(page)
            changed.append(f"glossary/register.md ({len(rows)} terms)")
    return changed


def _reparse(lines):
    CATALOG.write_text("\n".join(lines) + "\n")
    return read_readme_rows()


def category_taglines():
    """-> {category: italic tagline under its heading} from glossary/categories.md."""
    out, cat = {}, None
    for line in CATALOG.read_text().splitlines():
        m = SECTION_RE.match(line)
        if m:
            cat = m.group(1).strip()
            continue
        if cat and cat not in out and re.match(r"^\*[^*].*\*$", line.strip()):
            out[cat] = line.strip().strip("*")
    return out


def gh_anchor(heading):
    """GitHub's heading anchor: lowercase, punctuation dropped, spaces to hyphens."""
    return re.sub(r"[^a-z0-9 -]", "", heading.lower()).replace(" ", "-")


def key_terms_block(entries):
    """The README Concepts block, derived from inbound links and the catalog order."""
    _, rrows, rorder = read_readme_rows()
    texts = {e["slug"]: (CONCEPTS / f"{e['slug']}.md").read_text(encoding="utf-8") for e in entries}
    by_slug = {e["slug"]: e for e in entries}
    def inbound(slug):
        pat = re.compile(r"\]\((?:\.\./concepts/|concepts/)?" + re.escape(slug) + r"\.md[)#]")
        return sum(1 for s, txt in texts.items() if s != slug and pat.search(txt))
    tag = category_taglines()
    lines = [KEY_START, "", "| Category | Key terms | Browse |", "|---|---|---|"]
    for cat, slugs in rorder.items():
        pool = [s for s in slugs if s in by_slug and s not in KEY_TERMS_EXCLUDE]
        pinned = [s for s in KEY_TERMS_PIN.get(cat, []) if s in pool]
        rest = sorted((s for s in pool if s not in pinned),
                      key=lambda s: (-inbound(s), slugs.index(s)))
        picks = (pinned + rest)[:KEY_TERMS_N]
        terms = " · ".join(f"[{by_slug[s]['term']}](concepts/{s}.md)" for s in picks)
        head = f"**{cat}**" + (f"<br>*{tag[cat]}*" if cat in tag else "")
        lines.append(f"| {head} | {terms} | [All&nbsp;{len(pool)}&nbsp;→](glossary/categories.md#{gh_anchor(cat)}) |")
    lines += ["", KEY_END]
    return "\n".join(lines)


# ---------- reports ----------

def promise_gaps(entries):
    """Unlinked bullets in a Related concepts section.

    Higher-value than the gap report and structurally invisible to it: a bullet
    here is a promise the entry has already made, whereas a prose mention is
    only a usage. The gap report weights them identically, which buries the
    promises. Found by hand for the v1.18 batch (5 of 6 terms); automated after.
    """
    out = []
    for e in entries:
        body = (CONCEPTS / f"{e['slug']}.md").read_text()
        m = re.search(r"^## Related concepts\s*\n(.*?)(?=^## |\Z)", body, re.M | re.S)
        if not m:
            continue
        for line in m.group(1).splitlines():
            line = line.strip()
            if line.startswith("- ") and "](" not in line:
                out.append(f"  {e['slug']}: {line[2:]}")
    return out


def report(entries):
    # reverse index for Wiki-Sources col L
    #
    # notes/ is scanned here deliberately. A Sep 2026 audit of col L found 39 of
    # 256 rows factually wrong, systematically: 15 sources cited ONLY from a
    # notes/ page appeared in no row at all, because nothing outside concepts/
    # was ever looked at. Regenerating the column from this report is only safe
    # while this loop stays in — dropping it silently reintroduces that gap.
    rev = defaultdict(list)
    for e in entries:
        for s in e["sources"]:
            rev[s].append(e["slug"])
    notes_rev = defaultdict(set)
    for p in sorted((ROOT / "notes").glob("*.md")):
        for src in set(re.findall(r"\|\s*(SRC-\d+)\s*\|", p.read_text(encoding="utf-8"))):
            notes_rev[src].add(p.stem)
    print("== Wiki-Sources reverse index (col L) ==")
    for src in sorted(set(rev) | set(notes_rev)):
        parts = []
        if notes_rev.get(src):
            parts.append("notes: " + " · ".join(sorted(notes_rev[src])))
        parts += sorted(rev.get(src, []))
        print(f"{src}\t{' · '.join(parts)}")

    rev_review = inline_anchor_review(entries)
    print(f"\n== Inline anchors to eyeball ({len(rev_review)}) — paraphrase is fine, a wrong target is not ==")
    print("\n".join(rev_review) if rev_review else "  none")

    tc = Counter(t for e in entries for t in (e.get("tags") or []))
    print(f"\n== Tag distribution ({len(tc)} tags, {sum(tc.values())} assignments, "
          f"{sum(tc.values())/max(1,len(entries)):.1f}/entry) ==")
    for t, n in tc.most_common():
        flag = "  <- matches a third of the corpus; discriminates little" if n > len(entries) * 0.33 else ""
        print(f"{n:4d}  {t}{flag}")

    order = ["high", "medium-high", "medium", "low-medium", "low", "split"]
    cc = Counter(e["confidence"] for e in entries)
    sc = Counter(e.get("established") for e in entries)
    print(f"\n== Calibration ({len(entries)} entries) ==")
    print("  term status:  " + " · ".join(f"{sc[k]} {k}" for k in ("established","emerging","house","vendor") if sc.get(k)))
    print("  confidence:   " + " · ".join(f"{cc[k]} {k}" for k in order if cc.get(k)))
    split = sorted(e["term"] for e in entries if e["confidence"] == "split")
    print(f"  {len(split)} entries rate their own halves differently — a calibration signal, not a defect:")
    for s in split:
        print(f"     {s}")
    odd = sorted((e.get("established"), e["confidence"], e["term"]) for e in entries
                 if e.get("established") != "established")
    print("  non-established terms, with their evidence rating (the two axes are independent):")
    for s, c, term in odd:
        print(f"     {s:12} {c:12} {term}")

    pg = promise_gaps(entries)
    print(f"\n== Promised but unpublished ({len(pg)}) — Related-concepts bullets with no link ==")
    print("\n".join(pg) if pg else "  none — every Related-concepts bullet resolves")

    # gap report: unpublished candidate terms ranked by unlinked plain-text mentions
    rows = read_export()
    print("\n== Gap report ==")
    if not rows:
        print(f"(skipped — no {EXPORT.relative_to(ROOT)})")
        return
    published = {e["term"] for e in entries}
    corpus = {p: p.read_text() for p in CONCEPTS.glob("*.md")}
    corpus.update({p: p.read_text() for p in (ROOT / "notes").glob("*.md")})
    scored = []
    for term in (r["term"] for r in rows if not r["published"]):
        if term in published:
            continue
        n = sum(1 for text in corpus.values()
                for line in text.splitlines()
                if term in line and "](" not in line)
        scored.append((n, term))
    for n, term in sorted(scored, reverse=True):
        print(f"{n:3d}  {term}")
    flat = Counter(n for n, _ in scored)
    top = max(flat) if flat else 0
    print(f"\n{len(scored)} unpublished · top score {top} · "
          f"{flat.get(top,0)} tied at top"
          f"{'  <- tiebreak is FLAT, fall back to curation criteria' if flat.get(top,0) > 2 else ''}")


def main():
    cmd = sys.argv[1] if len(sys.argv) > 1 else "check"
    entries = load()
    if cmd == "check":
        problems = check(entries)
        if problems:
            print(f"{len(problems)} problem(s):")
            for p in problems:
                print(f"  {p}")
            return 1
        print(f"clean — {len(entries)} entries, "
              f"{sum(len(e['aliases']) for e in entries)} aliases, "
              f"README + glossary + counts + links + aliases all consistent")
        return 0
    if cmd == "write":
        changed = write(entries)
        print("\n".join(f"wrote {c}" for c in changed) if changed else "nothing to write")
        return 0
    if cmd == "report":
        report(entries)
        return 0
    print(__doc__)
    return 2


if __name__ == "__main__":
    sys.exit(main())
